# https://chatgpt.com/c/681fd5c7-e14c-8001-ad97-0ad424b53176
services:
  ollama:
    image: ollama/ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    # Závisí od: ollama – backend čaká, kým sa spustí.
    depends_on:
      - ollama
    # Exportovanie metriky pre Prometheus
    expose:
      - '8000'
    environment:
      - PROMETHEUS_ENABLE=true # backend vďaka tejto premennej vie, že má exportovať metriky.

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  # Služba Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # Služba Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  ollama_data:
  # prometheus_data:

networks:
  app_network:
    driver: bridge
