services:
  ollama:
    image: ollama/ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - ollama

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  ollama_data:
