services:
  ollama:
    image: ollama/ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - ollama
    # Exportovanie metriky pre Prometheus
    expose:
      - '8000'
    environment:
      - PROMETHEUS_ENABLE=true # Týmto môžeme signalizovať backendu, že metriky sa majú exportovať
    # Pridanie Prometheus exporteru pre backend aplikáciu (používaj knižnicu ako prometheus_fastapi_instrumentator)

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  # Služba Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
volumes:
  ollama_data:
  prometheus_data:

networks:
  app_network:
    driver: bridge
