apiVersion: v1
kind: Service
metadata:
  name: backend
# spec:
#   selector:
#     app: backend
#   ports:
#     - port: 8000
#       targetPort: 8000
#   type: ClusterIP
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
